<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Mahendra's Demo App</title>
  <style>
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      background: linear-gradient(135deg, #1e3c72, #2a5298);
      color: #fff;
      text-align: center;
      padding: 40px;
    }
    .container {
      background-color: rgba(255, 255, 255, 0.1);
      padding: 30px;
      border-radius: 12px;
      max-width: 700px;
      margin: auto;
      box-shadow: 0 4px 20px rgba(0, 0, 0, 0.3);
    }
    img {
      width: 300px;
      height: auto;
      margin-bottom: 20px;
    }
    h1 {
      color: #ffcc00;
      margin-bottom: 20px;
    }
    p {
      font-size: 18px;
      line-height: 1.6;
    }
    b {
      color: #00ffcc;
    }
    footer {
      margin-top: 30px;
      font-size: 14px;
      opacity: 0.8;
    }
  </style>
</head>
<body>
<?php
  function get_metadata($path) {
    $baseUrl = "http://169.254.169.254/latest/meta-data/";
    $tokenUrl = "http://169.254.169.254/latest/api/token";

    // Try IMDSv2
    $ch = curl_init($tokenUrl);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_TIMEOUT, 2);
    curl_setopt($ch, CURLOPT_HTTPHEADER, ["X-aws-ec2-metadata-token-ttl-seconds: 21600"]);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "PUT");
    $token = curl_exec($ch);
    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($httpCode == 200 && !empty($token)) {
      // IMDSv2 succeeded
      $ch = curl_init($baseUrl . $path);
      curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
      curl_setopt($ch, CURLOPT_TIMEOUT, 2);
      curl_setopt($ch, CURLOPT_HTTPHEADER, ["X-aws-ec2-metadata-token: $token"]);
      $result = curl_exec($ch);
      curl_close($ch);
      return $result ?: "Unavailable";
    } else {
      // Fallback to IMDSv1
      return @file_get_contents($baseUrl . $path) ?: "Unavailable";
    }
  }

  $instance = get_metadata("instance-id");
  $publicip = get_metadata("public-ipv4");
  $localip = get_metadata("local-ipv4");
  $az = get_metadata("placement/availability-zone");
  $region = get_metadata("placement/region");
?>
  <div class="container">
    <img src="https://download.logo.wine/logo/Amazon_Elastic_Compute_Cloud/Amazon_Elastic_Compute_Cloud-Logo.wine.png" alt="AWS EC2 Logo">
    <h1>Mahendra's EC2 Metadata Demo</h1>
    <p>This page was generated by instance <b><?= htmlspecialchars($instance) ?></b> in Availability Zone <b><?= htmlspecialchars($az) ?></b>.</p>
    <p>Instance Region: <b><?= htmlspecialchars($region) ?></b></p>
    <p>Instance Public IP: <b><?= htmlspecialchars($publicip) ?></b></p>
    <p>Instance Private IP: <b><?= htmlspecialchars($localip) ?></b></p>
    <footer>Powered by AWS EC2 • IMDSv2 Compatible</footer>
  </div>
</body>
</html>
