<html>
<title> Mahendra's Demo App </title>
<body>
<?php
  $urlRoot="http://169.254.169.254/latest/meta-data/";
  $instance = file_get_contents($urlRoot . 'instance-id');
  $publicip = file_get_contents($urlRoot . 'public-ipv4');
  $localip = file_get_contents($urlRoot . 'local-ipv4');
  $az = file_get_contents($urlRoot . 'placement/availability-zone');

?>

<br>
<IMG SRC="https://165halsey.com/wp-content/uploads/AWS-logo-Website.jpg" ALT="Demo Logo" width="270" height="200"><br>
<center><p style="font-family:verdana">This page was generated by instance <b><?= $instance ?></b> in Availability Zone <b><?= $az ?></b>.</p></center>
<center><p style="font-family:verdana">Instance Public IP: <b><?= $publicip ?></b></p></center>
<center><p style="font-family:verdana">Instance Private IP: <b><?= $localip ?></b></p></center>